### ISSUE TITLE
Adapt the configuration to 3.0

### ISSUE THREAD

**Issue by soyuka** [platformsh-templates/api-platform-api-admin#3]
See https://github.com/api-platform/api-platform/blob/main/api/config/packages/api_platform.yaml

**Comment by flovntp** [comment]
@soyuka 
Sorry, i didn't get what you mean by copy/pasting your link... 
please see original one (version 3) 
https://github.com/api-platform/api-platform/blob/v3.0.0/api/config/packages/api_platform.yaml
they are the same...

And please find the new version 3 template for API Platform. 
https://github.com/platformsh-templates/API-Platform-v3

**Comment by flovntp** [comment]
Feel free to reopen this issue if relevant.
